# {if:just}
# Build the firmware image
[group('firmware')]
fw-build:
    cd firmware && cargo build --release

# Flash the board (probe attached)
[group('firmware')]
flash:
    cd firmware && cargo run --release
# {endif:just}
