version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # {if:rust}
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      cargo-dependencies:
        patterns: ["*"]
  # {endif:rust}
  # {if:nix}
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      flake-inputs:
        patterns: ["*"]
# {endif:nix}
